import { StyleSheet } from "react-native";

/**
 * SPACING UTILITIES
 *
 * Padding, margin, gap, and space utilities
 * Based on Tailwind CSS spacing scale (0.25rem = 4px)
 */

export const spacingUtilities = StyleSheet.create({
  // ====================
  // PADDING UTILITIES
  // ====================

  // All Padding
  "p-0": { padding: 0 },
  "p-px": { padding: 1 },
  "p-0.5": { padding: 2 },
  "p-1": { padding: 4 },
  "p-1.5": { padding: 6 },
  "p-2": { padding: 8 },
  "p-2.5": { padding: 10 },
  "p-3": { padding: 12 },
  "p-3.5": { padding: 14 },
  "p-4": { padding: 16 },
  "p-5": { padding: 20 },
  "p-6": { padding: 24 },
  "p-7": { padding: 28 },
  "p-8": { padding: 32 },
  "p-9": { padding: 36 },
  "p-10": { padding: 40 },
  "p-11": { padding: 44 },
  "p-12": { padding: 48 },
  "p-14": { padding: 56 },
  "p-16": { padding: 64 },
  "p-20": { padding: 80 },
  "p-24": { padding: 96 },
  "p-28": { padding: 112 },
  "p-32": { padding: 128 },
  "p-36": { padding: 144 },
  "p-40": { padding: 160 },
  "p-44": { padding: 176 },
  "p-48": { padding: 192 },
  "p-52": { padding: 208 },
  "p-56": { padding: 224 },
  "p-60": { padding: 240 },
  "p-64": { padding: 256 },
  "p-72": { padding: 288 },
  "p-80": { padding: 320 },
  "p-96": { padding: 384 },

  // Horizontal Padding
  "px-0": { paddingHorizontal: 0 },
  "px-px": { paddingHorizontal: 1 },
  "px-0.5": { paddingHorizontal: 2 },
  "px-1": { paddingHorizontal: 4 },
  "px-1.5": { paddingHorizontal: 6 },
  "px-2": { paddingHorizontal: 8 },
  "px-2.5": { paddingHorizontal: 10 },
  "px-3": { paddingHorizontal: 12 },
  "px-3.5": { paddingHorizontal: 14 },
  "px-4": { paddingHorizontal: 16 },
  "px-5": { paddingHorizontal: 20 },
  "px-6": { paddingHorizontal: 24 },
  "px-7": { paddingHorizontal: 28 },
  "px-8": { paddingHorizontal: 32 },
  "px-9": { paddingHorizontal: 36 },
  "px-10": { paddingHorizontal: 40 },
  "px-11": { paddingHorizontal: 44 },
  "px-12": { paddingHorizontal: 48 },
  "px-14": { paddingHorizontal: 56 },
  "px-16": { paddingHorizontal: 64 },
  "px-20": { paddingHorizontal: 80 },
  "px-24": { paddingHorizontal: 96 },

  // Vertical Padding
  "py-0": { paddingVertical: 0 },
  "py-px": { paddingVertical: 1 },
  "py-0.5": { paddingVertical: 2 },
  "py-1": { paddingVertical: 4 },
  "py-1.5": { paddingVertical: 6 },
  "py-2": { paddingVertical: 8 },
  "py-2.5": { paddingVertical: 10 },
  "py-3": { paddingVertical: 12 },
  "py-3.5": { paddingVertical: 14 },
  "py-4": { paddingVertical: 16 },
  "py-5": { paddingVertical: 20 },
  "py-6": { paddingVertical: 24 },
  "py-7": { paddingVertical: 28 },
  "py-8": { paddingVertical: 32 },
  "py-9": { paddingVertical: 36 },
  "py-10": { paddingVertical: 40 },
  "py-11": { paddingVertical: 44 },
  "py-12": { paddingVertical: 48 },
  "py-14": { paddingVertical: 56 },
  "py-16": { paddingVertical: 64 },
  "py-20": { paddingVertical: 80 },
  "py-24": { paddingVertical: 96 },

  // Individual Padding - Top
  "pt-0": { paddingTop: 0 },
  "pt-px": { paddingTop: 1 },
  "pt-0.5": { paddingTop: 2 },
  "pt-1": { paddingTop: 4 },
  "pt-1.5": { paddingTop: 6 },
  "pt-2": { paddingTop: 8 },
  "pt-2.5": { paddingTop: 10 },
  "pt-3": { paddingTop: 12 },
  "pt-3.5": { paddingTop: 14 },
  "pt-4": { paddingTop: 16 },
  "pt-5": { paddingTop: 20 },
  "pt-6": { paddingTop: 24 },
  "pt-7": { paddingTop: 28 },
  "pt-8": { paddingTop: 32 },
  "pt-9": { paddingTop: 36 },
  "pt-10": { paddingTop: 40 },
  "pt-11": { paddingTop: 44 },
  "pt-12": { paddingTop: 48 },
  "pt-14": { paddingTop: 56 },
  "pt-16": { paddingTop: 64 },
  "pt-20": { paddingTop: 80 },
  "pt-24": { paddingTop: 96 },

  // Individual Padding - Right
  "pr-0": { paddingRight: 0 },
  "pr-px": { paddingRight: 1 },
  "pr-0.5": { paddingRight: 2 },
  "pr-1": { paddingRight: 4 },
  "pr-1.5": { paddingRight: 6 },
  "pr-2": { paddingRight: 8 },
  "pr-2.5": { paddingRight: 10 },
  "pr-3": { paddingRight: 12 },
  "pr-3.5": { paddingRight: 14 },
  "pr-4": { paddingRight: 16 },
  "pr-5": { paddingRight: 20 },
  "pr-6": { paddingRight: 24 },
  "pr-7": { paddingRight: 28 },
  "pr-8": { paddingRight: 32 },
  "pr-9": { paddingRight: 36 },
  "pr-10": { paddingRight: 40 },
  "pr-11": { paddingRight: 44 },
  "pr-12": { paddingRight: 48 },
  "pr-14": { paddingRight: 56 },
  "pr-16": { paddingRight: 64 },
  "pr-20": { paddingRight: 80 },
  "pr-24": { paddingRight: 96 },

  // Individual Padding - Bottom
  "pb-0": { paddingBottom: 0 },
  "pb-px": { paddingBottom: 1 },
  "pb-0.5": { paddingBottom: 2 },
  "pb-1": { paddingBottom: 4 },
  "pb-1.5": { paddingBottom: 6 },
  "pb-2": { paddingBottom: 8 },
  "pb-2.5": { paddingBottom: 10 },
  "pb-3": { paddingBottom: 12 },
  "pb-3.5": { paddingBottom: 14 },
  "pb-4": { paddingBottom: 16 },
  "pb-5": { paddingBottom: 20 },
  "pb-6": { paddingBottom: 24 },
  "pb-7": { paddingBottom: 28 },
  "pb-8": { paddingBottom: 32 },
  "pb-9": { paddingBottom: 36 },
  "pb-10": { paddingBottom: 40 },
  "pb-11": { paddingBottom: 44 },
  "pb-12": { paddingBottom: 48 },
  "pb-14": { paddingBottom: 56 },
  "pb-16": { paddingBottom: 64 },
  "pb-20": { paddingBottom: 80 },
  "pb-24": { paddingBottom: 96 },

  // Individual Padding - Left
  "pl-0": { paddingLeft: 0 },
  "pl-px": { paddingLeft: 1 },
  "pl-0.5": { paddingLeft: 2 },
  "pl-1": { paddingLeft: 4 },
  "pl-1.5": { paddingLeft: 6 },
  "pl-2": { paddingLeft: 8 },
  "pl-2.5": { paddingLeft: 10 },
  "pl-3": { paddingLeft: 12 },
  "pl-3.5": { paddingLeft: 14 },
  "pl-4": { paddingLeft: 16 },
  "pl-5": { paddingLeft: 20 },
  "pl-6": { paddingLeft: 24 },
  "pl-7": { paddingLeft: 28 },
  "pl-8": { paddingLeft: 32 },
  "pl-9": { paddingLeft: 36 },
  "pl-10": { paddingLeft: 40 },
  "pl-11": { paddingLeft: 44 },
  "pl-12": { paddingLeft: 48 },
  "pl-14": { paddingLeft: 56 },
  "pl-16": { paddingLeft: 64 },
  "pl-20": { paddingLeft: 80 },
  "pl-24": { paddingLeft: 96 },

  // ====================
  // MARGIN UTILITIES
  // ====================

  // All Margin
  "m-0": { margin: 0 },
  "m-px": { margin: 1 },
  "m-0.5": { margin: 2 },
  "m-1": { margin: 4 },
  "m-1.5": { margin: 6 },
  "m-2": { margin: 8 },
  "m-2.5": { margin: 10 },
  "m-3": { margin: 12 },
  "m-3.5": { margin: 14 },
  "m-4": { margin: 16 },
  "m-5": { margin: 20 },
  "m-6": { margin: 24 },
  "m-7": { margin: 28 },
  "m-8": { margin: 32 },
  "m-9": { margin: 36 },
  "m-10": { margin: 40 },
  "m-11": { margin: 44 },
  "m-12": { margin: 48 },
  "m-14": { margin: 56 },
  "m-16": { margin: 64 },
  "m-20": { margin: 80 },
  "m-24": { margin: 96 },
  "m-28": { margin: 112 },
  "m-32": { margin: 128 },
  "m-36": { margin: 144 },
  "m-40": { margin: 160 },
  "m-44": { margin: 176 },
  "m-48": { margin: 192 },
  "m-52": { margin: 208 },
  "m-56": { margin: 224 },
  "m-60": { margin: 240 },
  "m-64": { margin: 256 },
  "m-72": { margin: 288 },
  "m-80": { margin: 320 },
  "m-96": { margin: 384 },
  "m-auto": { margin: "auto" },

  // Horizontal Margin
  "mx-0": { marginHorizontal: 0 },
  "mx-px": { marginHorizontal: 1 },
  "mx-0.5": { marginHorizontal: 2 },
  "mx-1": { marginHorizontal: 4 },
  "mx-1.5": { marginHorizontal: 6 },
  "mx-2": { marginHorizontal: 8 },
  "mx-2.5": { marginHorizontal: 10 },
  "mx-3": { marginHorizontal: 12 },
  "mx-3.5": { marginHorizontal: 14 },
  "mx-4": { marginHorizontal: 16 },
  "mx-5": { marginHorizontal: 20 },
  "mx-6": { marginHorizontal: 24 },
  "mx-7": { marginHorizontal: 28 },
  "mx-8": { marginHorizontal: 32 },
  "mx-9": { marginHorizontal: 36 },
  "mx-10": { marginHorizontal: 40 },
  "mx-11": { marginHorizontal: 44 },
  "mx-12": { marginHorizontal: 48 },
  "mx-14": { marginHorizontal: 56 },
  "mx-16": { marginHorizontal: 64 },
  "mx-20": { marginHorizontal: 80 },
  "mx-24": { marginHorizontal: 96 },
  "mx-auto": { marginHorizontal: "auto" },

  // Vertical Margin
  "my-0": { marginVertical: 0 },
  "my-px": { marginVertical: 1 },
  "my-0.5": { marginVertical: 2 },
  "my-1": { marginVertical: 4 },
  "my-1.5": { marginVertical: 6 },
  "my-2": { marginVertical: 8 },
  "my-2.5": { marginVertical: 10 },
  "my-3": { marginVertical: 12 },
  "my-3.5": { marginVertical: 14 },
  "my-4": { marginVertical: 16 },
  "my-5": { marginVertical: 20 },
  "my-6": { marginVertical: 24 },
  "my-7": { marginVertical: 28 },
  "my-8": { marginVertical: 32 },
  "my-9": { marginVertical: 36 },
  "my-10": { marginVertical: 40 },
  "my-11": { marginVertical: 44 },
  "my-12": { marginVertical: 48 },
  "my-14": { marginVertical: 56 },
  "my-16": { marginVertical: 64 },
  "my-20": { marginVertical: 80 },
  "my-24": { marginVertical: 96 },
  "my-auto": { marginVertical: "auto" },

  // Individual Margin - Top
  "mt-0": { marginTop: 0 },
  "mt-px": { marginTop: 1 },
  "mt-0.5": { marginTop: 2 },
  "mt-1": { marginTop: 4 },
  "mt-1.5": { marginTop: 6 },
  "mt-2": { marginTop: 8 },
  "mt-2.5": { marginTop: 10 },
  "mt-3": { marginTop: 12 },
  "mt-3.5": { marginTop: 14 },
  "mt-4": { marginTop: 16 },
  "mt-5": { marginTop: 20 },
  "mt-6": { marginTop: 24 },
  "mt-7": { marginTop: 28 },
  "mt-8": { marginTop: 32 },
  "mt-9": { marginTop: 36 },
  "mt-10": { marginTop: 40 },
  "mt-11": { marginTop: 44 },
  "mt-12": { marginTop: 48 },
  "mt-14": { marginTop: 56 },
  "mt-16": { marginTop: 64 },
  "mt-20": { marginTop: 80 },
  "mt-24": { marginTop: 96 },
  "mt-auto": { marginTop: "auto" },

  // Individual Margin - Right
  "mr-0": { marginRight: 0 },
  "mr-px": { marginRight: 1 },
  "mr-0.5": { marginRight: 2 },
  "mr-1": { marginRight: 4 },
  "mr-1.5": { marginRight: 6 },
  "mr-2": { marginRight: 8 },
  "mr-2.5": { marginRight: 10 },
  "mr-3": { marginRight: 12 },
  "mr-3.5": { marginRight: 14 },
  "mr-4": { marginRight: 16 },
  "mr-5": { marginRight: 20 },
  "mr-6": { marginRight: 24 },
  "mr-7": { marginRight: 28 },
  "mr-8": { marginRight: 32 },
  "mr-9": { marginRight: 36 },
  "mr-10": { marginRight: 40 },
  "mr-11": { marginRight: 44 },
  "mr-12": { marginRight: 48 },
  "mr-14": { marginRight: 56 },
  "mr-16": { marginRight: 64 },
  "mr-20": { marginRight: 80 },
  "mr-24": { marginRight: 96 },
  "mr-auto": { marginRight: "auto" },

  // Individual Margin - Bottom
  "mb-0": { marginBottom: 0 },
  "mb-px": { marginBottom: 1 },
  "mb-0.5": { marginBottom: 2 },
  "mb-1": { marginBottom: 4 },
  "mb-1.5": { marginBottom: 6 },
  "mb-2": { marginBottom: 8 },
  "mb-2.5": { marginBottom: 10 },
  "mb-3": { marginBottom: 12 },
  "mb-3.5": { marginBottom: 14 },
  "mb-4": { marginBottom: 16 },
  "mb-5": { marginBottom: 20 },
  "mb-6": { marginBottom: 24 },
  "mb-7": { marginBottom: 28 },
  "mb-8": { marginBottom: 32 },
  "mb-9": { marginBottom: 36 },
  "mb-10": { marginBottom: 40 },
  "mb-11": { marginBottom: 44 },
  "mb-12": { marginBottom: 48 },
  "mb-14": { marginBottom: 56 },
  "mb-16": { marginBottom: 64 },
  "mb-20": { marginBottom: 80 },
  "mb-24": { marginBottom: 96 },
  "mb-auto": { marginBottom: "auto" },

  // Individual Margin - Left
  "ml-0": { marginLeft: 0 },
  "ml-px": { marginLeft: 1 },
  "ml-0.5": { marginLeft: 2 },
  "ml-1": { marginLeft: 4 },
  "ml-1.5": { marginLeft: 6 },
  "ml-2": { marginLeft: 8 },
  "ml-2.5": { marginLeft: 10 },
  "ml-3": { marginLeft: 12 },
  "ml-3.5": { marginLeft: 14 },
  "ml-4": { marginLeft: 16 },
  "ml-5": { marginLeft: 20 },
  "ml-6": { marginLeft: 24 },
  "ml-7": { marginLeft: 28 },
  "ml-8": { marginLeft: 32 },
  "ml-9": { marginLeft: 36 },
  "ml-10": { marginLeft: 40 },
  "ml-11": { marginLeft: 44 },
  "ml-12": { marginLeft: 48 },
  "ml-14": { marginLeft: 56 },
  "ml-16": { marginLeft: 64 },
  "ml-20": { marginLeft: 80 },
  "ml-24": { marginLeft: 96 },
  "ml-auto": { marginLeft: "auto" },

  // ====================
  // NEGATIVE MARGINS
  // ====================

  // Negative All Margin
  "-m-0": { margin: 0 },
  "-m-px": { margin: -1 },
  "-m-0.5": { margin: -2 },
  "-m-1": { margin: -4 },
  "-m-1.5": { margin: -6 },
  "-m-2": { margin: -8 },
  "-m-2.5": { margin: -10 },
  "-m-3": { margin: -12 },
  "-m-3.5": { margin: -14 },
  "-m-4": { margin: -16 },
  "-m-5": { margin: -20 },
  "-m-6": { margin: -24 },
  "-m-7": { margin: -28 },
  "-m-8": { margin: -32 },
  "-m-9": { margin: -36 },
  "-m-10": { margin: -40 },
  "-m-11": { margin: -44 },
  "-m-12": { margin: -48 },
  "-m-14": { margin: -56 },
  "-m-16": { margin: -64 },
  "-m-20": { margin: -80 },
  "-m-24": { margin: -96 },

  // Negative Horizontal Margin
  "-mx-0": { marginHorizontal: 0 },
  "-mx-px": { marginHorizontal: -1 },
  "-mx-0.5": { marginHorizontal: -2 },
  "-mx-1": { marginHorizontal: -4 },
  "-mx-1.5": { marginHorizontal: -6 },
  "-mx-2": { marginHorizontal: -8 },
  "-mx-2.5": { marginHorizontal: -10 },
  "-mx-3": { marginHorizontal: -12 },
  "-mx-3.5": { marginHorizontal: -14 },
  "-mx-4": { marginHorizontal: -16 },
  "-mx-5": { marginHorizontal: -20 },
  "-mx-6": { marginHorizontal: -24 },
  "-mx-7": { marginHorizontal: -28 },
  "-mx-8": { marginHorizontal: -32 },
  "-mx-9": { marginHorizontal: -36 },
  "-mx-10": { marginHorizontal: -40 },
  "-mx-11": { marginHorizontal: -44 },
  "-mx-12": { marginHorizontal: -48 },
  "-mx-14": { marginHorizontal: -56 },
  "-mx-16": { marginHorizontal: -64 },
  "-mx-20": { marginHorizontal: -80 },
  "-mx-24": { marginHorizontal: -96 },

  // Negative Vertical Margin
  "-my-0": { marginVertical: 0 },
  "-my-px": { marginVertical: -1 },
  "-my-0.5": { marginVertical: -2 },
  "-my-1": { marginVertical: -4 },
  "-my-1.5": { marginVertical: -6 },
  "-my-2": { marginVertical: -8 },
  "-my-2.5": { marginVertical: -10 },
  "-my-3": { marginVertical: -12 },
  "-my-3.5": { marginVertical: -14 },
  "-my-4": { marginVertical: -16 },
  "-my-5": { marginVertical: -20 },
  "-my-6": { marginVertical: -24 },
  "-my-7": { marginVertical: -28 },
  "-my-8": { marginVertical: -32 },
  "-my-9": { marginVertical: -36 },
  "-my-10": { marginVertical: -40 },
  "-my-11": { marginVertical: -44 },
  "-my-12": { marginVertical: -48 },
  "-my-14": { marginVertical: -56 },
  "-my-16": { marginVertical: -64 },
  "-my-20": { marginVertical: -80 },
  "-my-24": { marginVertical: -96 },

  // Negative Individual Margins
  "-mt-0": { marginTop: 0 },
  "-mt-px": { marginTop: -1 },
  "-mt-0.5": { marginTop: -2 },
  "-mt-1": { marginTop: -4 },
  "-mt-2": { marginTop: -8 },
  "-mt-3": { marginTop: -12 },
  "-mt-4": { marginTop: -16 },
  "-mt-5": { marginTop: -20 },
  "-mt-6": { marginTop: -24 },
  "-mt-8": { marginTop: -32 },
  "-mt-10": { marginTop: -40 },
  "-mt-12": { marginTop: -48 },
  "-mt-16": { marginTop: -64 },
  "-mt-20": { marginTop: -80 },
  "-mt-24": { marginTop: -96 },

  "-mr-0": { marginRight: 0 },
  "-mr-px": { marginRight: -1 },
  "-mr-0.5": { marginRight: -2 },
  "-mr-1": { marginRight: -4 },
  "-mr-2": { marginRight: -8 },
  "-mr-3": { marginRight: -12 },
  "-mr-4": { marginRight: -16 },
  "-mr-5": { marginRight: -20 },
  "-mr-6": { marginRight: -24 },
  "-mr-8": { marginRight: -32 },
  "-mr-10": { marginRight: -40 },
  "-mr-12": { marginRight: -48 },
  "-mr-16": { marginRight: -64 },
  "-mr-20": { marginRight: -80 },
  "-mr-24": { marginRight: -96 },

  "-mb-0": { marginBottom: 0 },
  "-mb-px": { marginBottom: -1 },
  "-mb-0.5": { marginBottom: -2 },
  "-mb-1": { marginBottom: -4 },
  "-mb-2": { marginBottom: -8 },
  "-mb-3": { marginBottom: -12 },
  "-mb-4": { marginBottom: -16 },
  "-mb-5": { marginBottom: -20 },
  "-mb-6": { marginBottom: -24 },
  "-mb-8": { marginBottom: -32 },
  "-mb-10": { marginBottom: -40 },
  "-mb-12": { marginBottom: -48 },
  "-mb-16": { marginBottom: -64 },
  "-mb-20": { marginBottom: -80 },
  "-mb-24": { marginBottom: -96 },

  "-ml-0": { marginLeft: 0 },
  "-ml-px": { marginLeft: -1 },
  "-ml-0.5": { marginLeft: -2 },
  "-ml-1": { marginLeft: -4 },
  "-ml-2": { marginLeft: -8 },
  "-ml-3": { marginLeft: -12 },
  "-ml-4": { marginLeft: -16 },
  "-ml-5": { marginLeft: -20 },
  "-ml-6": { marginLeft: -24 },
  "-ml-8": { marginLeft: -32 },
  "-ml-10": { marginLeft: -40 },
  "-ml-12": { marginLeft: -48 },
  "-ml-16": { marginLeft: -64 },
  "-ml-20": { marginLeft: -80 },
  "-ml-24": { marginLeft: -96 },

  // ====================
  // GAP UTILITIES
  // ====================

  "gap-0": { gap: 0 },
  "gap-px": { gap: 1 },
  "gap-0.5": { gap: 2 },
  "gap-1": { gap: 4 },
  "gap-1.5": { gap: 6 },
  "gap-2": { gap: 8 },
  "gap-2.5": { gap: 10 },
  "gap-3": { gap: 12 },
  "gap-3.5": { gap: 14 },
  "gap-4": { gap: 16 },
  "gap-5": { gap: 20 },
  "gap-6": { gap: 24 },
  "gap-7": { gap: 28 },
  "gap-8": { gap: 32 },
  "gap-9": { gap: 36 },
  "gap-10": { gap: 40 },
  "gap-11": { gap: 44 },
  "gap-12": { gap: 48 },
  "gap-14": { gap: 56 },
  "gap-16": { gap: 64 },
  "gap-20": { gap: 80 },
  "gap-24": { gap: 96 },
  "gap-28": { gap: 112 },
  "gap-32": { gap: 128 },
  "gap-36": { gap: 144 },
  "gap-40": { gap: 160 },
  "gap-44": { gap: 176 },
  "gap-48": { gap: 192 },
  "gap-52": { gap: 208 },
  "gap-56": { gap: 224 },
  "gap-60": { gap: 240 },
  "gap-64": { gap: 256 },
  "gap-72": { gap: 288 },
  "gap-80": { gap: 320 },
  "gap-96": { gap: 384 },

  // Gap X (row gap in flexbox)
  "gap-x-0": { columnGap: 0 },
  "gap-x-px": { columnGap: 1 },
  "gap-x-0.5": { columnGap: 2 },
  "gap-x-1": { columnGap: 4 },
  "gap-x-1.5": { columnGap: 6 },
  "gap-x-2": { columnGap: 8 },
  "gap-x-2.5": { columnGap: 10 },
  "gap-x-3": { columnGap: 12 },
  "gap-x-3.5": { columnGap: 14 },
  "gap-x-4": { columnGap: 16 },
  "gap-x-5": { columnGap: 20 },
  "gap-x-6": { columnGap: 24 },
  "gap-x-7": { columnGap: 28 },
  "gap-x-8": { columnGap: 32 },
  "gap-x-9": { columnGap: 36 },
  "gap-x-10": { columnGap: 40 },
  "gap-x-11": { columnGap: 44 },
  "gap-x-12": { columnGap: 48 },
  "gap-x-14": { columnGap: 56 },
  "gap-x-16": { columnGap: 64 },
  "gap-x-20": { columnGap: 80 },
  "gap-x-24": { columnGap: 96 },

  // Gap Y (column gap in flexbox)
  "gap-y-0": { rowGap: 0 },
  "gap-y-px": { rowGap: 1 },
  "gap-y-0.5": { rowGap: 2 },
  "gap-y-1": { rowGap: 4 },
  "gap-y-1.5": { rowGap: 6 },
  "gap-y-2": { rowGap: 8 },
  "gap-y-2.5": { rowGap: 10 },
  "gap-y-3": { rowGap: 12 },
  "gap-y-3.5": { rowGap: 14 },
  "gap-y-4": { rowGap: 16 },
  "gap-y-5": { rowGap: 20 },
  "gap-y-6": { rowGap: 24 },
  "gap-y-7": { rowGap: 28 },
  "gap-y-8": { rowGap: 32 },
  "gap-y-9": { rowGap: 36 },
  "gap-y-10": { rowGap: 40 },
  "gap-y-11": { rowGap: 44 },
  "gap-y-12": { rowGap: 48 },
  "gap-y-14": { rowGap: 56 },
  "gap-y-16": { rowGap: 64 },
  "gap-y-20": { rowGap: 80 },
  "gap-y-24": { rowGap: 96 },

  // ====================
  // SPACE UTILITIES (for flex containers)
  // ====================
  // Note: In React Native, use gap instead of space utilities
  // These utilities are mapped to gap for better React Native compatibility

  "space-x-0": { columnGap: 0 },
  "space-x-px": { columnGap: 1 },
  "space-x-0.5": { columnGap: 2 },
  "space-x-1": { columnGap: 4 },
  "space-x-1.5": { columnGap: 6 },
  "space-x-2": { columnGap: 8 },
  "space-x-2.5": { columnGap: 10 },
  "space-x-3": { columnGap: 12 },
  "space-x-3.5": { columnGap: 14 },
  "space-x-4": { columnGap: 16 },
  "space-x-5": { columnGap: 20 },
  "space-x-6": { columnGap: 24 },
  "space-x-7": { columnGap: 28 },
  "space-x-8": { columnGap: 32 },

  "space-y-0": { rowGap: 0 },
  "space-y-px": { rowGap: 1 },
  "space-y-0.5": { rowGap: 2 },
  "space-y-1": { rowGap: 4 },
  "space-y-1.5": { rowGap: 6 },
  "space-y-2": { rowGap: 8 },
  "space-y-2.5": { rowGap: 10 },
  "space-y-3": { rowGap: 12 },
  "space-y-3.5": { rowGap: 14 },
  "space-y-4": { rowGap: 16 },
  "space-y-5": { rowGap: 20 },
  "space-y-6": { rowGap: 24 },
  "space-y-7": { rowGap: 28 },
  "space-y-8": { rowGap: 32 },

  // ====================
  // CAMELCASE VERSIONS
  // ====================

  // Padding
  p0: { padding: 0 },
  p1: { padding: 4 },
  p2: { padding: 8 },
  p3: { padding: 12 },
  p4: { padding: 16 },
  p5: { padding: 20 },
  p6: { padding: 24 },
  p8: { padding: 32 },
  p10: { padding: 40 },
  p12: { padding: 48 },
  p16: { padding: 64 },
  p20: { padding: 80 },
  p24: { padding: 96 },

  px0: { paddingHorizontal: 0 },
  px1: { paddingHorizontal: 4 },
  px2: { paddingHorizontal: 8 },
  px3: { paddingHorizontal: 12 },
  px4: { paddingHorizontal: 16 },
  px5: { paddingHorizontal: 20 },
  px6: { paddingHorizontal: 24 },
  px8: { paddingHorizontal: 32 },

  py0: { paddingVertical: 0 },
  py1: { paddingVertical: 4 },
  py2: { paddingVertical: 8 },
  py3: { paddingVertical: 12 },
  py4: { paddingVertical: 16 },
  py5: { paddingVertical: 20 },
  py6: { paddingVertical: 24 },
  py8: { paddingVertical: 32 },

  pt0: { paddingTop: 0 },
  pt1: { paddingTop: 4 },
  pt2: { paddingTop: 8 },
  pt3: { paddingTop: 12 },
  pt4: { paddingTop: 16 },
  pt5: { paddingTop: 20 },
  pt6: { paddingTop: 24 },
  pt8: { paddingTop: 32 },

  pr0: { paddingRight: 0 },
  pr1: { paddingRight: 4 },
  pr2: { paddingRight: 8 },
  pr3: { paddingRight: 12 },
  pr4: { paddingRight: 16 },
  pr5: { paddingRight: 20 },
  pr6: { paddingRight: 24 },
  pr8: { paddingRight: 32 },

  pb0: { paddingBottom: 0 },
  pb1: { paddingBottom: 4 },
  pb2: { paddingBottom: 8 },
  pb3: { paddingBottom: 12 },
  pb4: { paddingBottom: 16 },
  pb5: { paddingBottom: 20 },
  pb6: { paddingBottom: 24 },
  pb8: { paddingBottom: 32 },

  pl0: { paddingLeft: 0 },
  pl1: { paddingLeft: 4 },
  pl2: { paddingLeft: 8 },
  pl3: { paddingLeft: 12 },
  pl4: { paddingLeft: 16 },
  pl5: { paddingLeft: 20 },
  pl6: { paddingLeft: 24 },
  pl8: { paddingLeft: 32 },

  // Margin
  m0: { margin: 0 },
  m1: { margin: 4 },
  m2: { margin: 8 },
  m3: { margin: 12 },
  m4: { margin: 16 },
  m5: { margin: 20 },
  m6: { margin: 24 },
  m8: { margin: 32 },
  mAuto: { margin: "auto" },

  mx0: { marginHorizontal: 0 },
  mx1: { marginHorizontal: 4 },
  mx2: { marginHorizontal: 8 },
  mx4: { marginHorizontal: 16 },
  mxAuto: { marginHorizontal: "auto" },

  my0: { marginVertical: 0 },
  my1: { marginVertical: 4 },
  my2: { marginVertical: 8 },
  my4: { marginVertical: 16 },

  mt0: { marginTop: 0 },
  mt1: { marginTop: 4 },
  mt2: { marginTop: 8 },
  mt3: { marginTop: 12 },
  mt4: { marginTop: 16 },
  mt5: { marginTop: 20 },
  mt6: { marginTop: 24 },
  mt8: { marginTop: 32 },
  mtAuto: { marginTop: "auto" },

  mr0: { marginRight: 0 },
  mr1: { marginRight: 4 },
  mr2: { marginRight: 8 },
  mr3: { marginRight: 12 },
  mr4: { marginRight: 16 },
  mr5: { marginRight: 20 },
  mr6: { marginRight: 24 },
  mr8: { marginRight: 32 },
  mrAuto: { marginRight: "auto" },

  mb0: { marginBottom: 0 },
  mb1: { marginBottom: 4 },
  mb2: { marginBottom: 8 },
  mb3: { marginBottom: 12 },
  mb4: { marginBottom: 16 },
  mb5: { marginBottom: 20 },
  mb6: { marginBottom: 24 },
  mb8: { marginBottom: 32 },
  mbAuto: { marginBottom: "auto" },

  ml0: { marginLeft: 0 },
  ml1: { marginLeft: 4 },
  ml2: { marginLeft: 8 },
  ml3: { marginLeft: 12 },
  ml4: { marginLeft: 16 },
  ml5: { marginLeft: 20 },
  ml6: { marginLeft: 24 },
  ml8: { marginLeft: 32 },
  mlAuto: { marginLeft: "auto" },

  // Negative Margins (CamelCase)
  negM1: { margin: -4 },
  negM2: { margin: -8 },
  negM3: { margin: -12 },
  negM4: { margin: -16 },
  negM5: { margin: -20 },
  negM6: { margin: -24 },
  negM8: { margin: -32 },
  negM10: { margin: -40 },
  negM12: { margin: -48 },
  negM16: { margin: -64 },
  negM20: { margin: -80 },
  negM24: { margin: -96 },

  negMx1: { marginHorizontal: -4 },
  negMx2: { marginHorizontal: -8 },
  negMx3: { marginHorizontal: -12 },
  negMx4: { marginHorizontal: -16 },
  negMx5: { marginHorizontal: -20 },
  negMx6: { marginHorizontal: -24 },
  negMx8: { marginHorizontal: -32 },
  negMx10: { marginHorizontal: -40 },
  negMx12: { marginHorizontal: -48 },
  negMx16: { marginHorizontal: -64 },
  negMx20: { marginHorizontal: -80 },
  negMx24: { marginHorizontal: -96 },

  negMy1: { marginVertical: -4 },
  negMy2: { marginVertical: -8 },
  negMy3: { marginVertical: -12 },
  negMy4: { marginVertical: -16 },
  negMy5: { marginVertical: -20 },
  negMy6: { marginVertical: -24 },
  negMy8: { marginVertical: -32 },
  negMy10: { marginVertical: -40 },
  negMy12: { marginVertical: -48 },
  negMy16: { marginVertical: -64 },
  negMy20: { marginVertical: -80 },
  negMy24: { marginVertical: -96 },

  // Gap utilities (CamelCase)
  gap0: { gap: 0 },
  gap1: { gap: 4 },
  gap2: { gap: 8 },
  gap3: { gap: 12 },
  gap4: { gap: 16 },
  gap5: { gap: 20 },
  gap6: { gap: 24 },
  gap8: { gap: 32 },
  gap10: { gap: 40 },
  gap12: { gap: 48 },
  gap16: { gap: 64 },
  gap20: { gap: 80 },
  gap24: { gap: 96 },
});
